# na wszelki wypadek import biblioteki widgetów, bo czasami wywalało błędy
import ipywidgets as widgets

# widget wyboru głównej kategorii
main_category = widgets.Dropdown(
    options=['Art',
             'Fashion',
             'Music',
             'Crafts',
             'Photography',
             'Design',
             'Film & Video',
             'Food',
             'Journalism',
             'Publishing',
             'Dance',
             'Comics',
             'Technology',
             'Theater',
             'Games'],
    description='M. category',
    disabled=False,)

# widget wyboru podkategorii, który tworzy się na podstawie wyboru głównej kategorii
sub_category = widgets.Dropdown(
    description="Category")

# o tutaj jest funkcja, która wykorzystuje słownik zbudowany na zasadzie {główne kategorie: adekwatne podkategorie}, 
# żeby ustawić w dropdownie odpowiednie podkategorie
# (to jest ogólnie de facto tak, że tworzymy zmienne typu widget, które mają odpowiednie parametry)
def narrow_subcat(*args):
    sub_categories = {'Art': 
                      ['Sculpture',
                       'Conceptual Art',
                       'Illustration',
                       'Public Art',
                       'Mixed Media',
                       'Video Art',
                       'Art',
                       'Installations',
                       'Ceramics',
                       'Textiles',
                       'Painting',
                       'Digital Art',
                       'Performance Art',
                       'not considered',
             'not considered'],
                      'Comics': 
                      ['Comic Books',
                       'Events',
                       'Anthologies',
                       'Graphic Novels',
                       'Comics',
                       'Webcomics',
             'not considered'],
                      'Crafts':
                      ['Weaving',
                       'Letterpress',
                       'Crochet',
                       'Candles',
                       'Taxidermy',
                       'Crafts',
                       'Knitting',
                       'Embroidery',
                       'Pottery',
                       'Glass',
                       'Quilts',
                       'Printing',
                       'DIY',
                       'Stationery',
                       'Woodworking',
             'not considered'],
                      'Dance': 
                      ['Dance',
                       'Spaces',
                       'Residencies',
                       'Workshops',
                       'Performances',
             'not considered'],
                      'Design': 
                      ['Graphic Design',
                       'Product Design',
                       'Civic Design',
                       'Interactive Design',
                       'Architecture',
                       'Typography',
                       'Design',
             'not considered'],
                      'Fashion': 
                      ['Couture',
                         'Childrenswear',
                         'Footwear',
                         'Fashion',
                         'Accessories',
                         'Jewelry',
                         'Apparel',
                         'Ready-to-wear',
                         'Pet Fashion',
             'not considered'],
                      'Film & Video': 
                      ['Television',
                         'Horror',
                         'Film & Video',
                         'Science Fiction',
                         'Music Videos',
                         'Documentary',
                         'Family',
                         'Animation',
                         'Fantasy',
                         'Experimental',
                         'Movie Theaters',
                         'Comedy',
                         'Webseries',
                         'Festivals',
                         'Romance',
                         'Drama',
                         'Shorts',
                         'Narrative Film',
                         'Thrillers',
                         'Action',
             'not considered'],
                      'Food': 
                      ['Spaces',
                         'Vegan',
                         'Drinks',
                         'Restaurants',
                         'Food',
                         'Events',
                         'Farms',
                         'Cookbooks',
                         "Farmer's Markets",
                         'Food Trucks',
                         'Community Gardens',
                         'Small Batch',
                         'Bacon',
             'not considered'],
                      'Games': 
                      ['Playing Cards',
                         'Puzzles',
                         'Games',
                         'Mobile Games',
                         'Gaming Hardware',
                         'Video Games',
                         'Tabletop Games',
                         'Live Games',
             'not considered'],
                      'Journalism': 
                      ['Print', 
                           'Video', 
                           'Journalism', 
                           'Web', 
                           'Photo',
                           'Audio',
             'not considered'],
                      'Music': 
                      ['Classical Music',
                         'Faith',
                         'Chiptune',
                         'Blues',
                         'Indie Rock',
                         'Pop',
                         'Kids',
                         'Hip-Hop',
                         'World Music',
                         'Jazz',
                         'Latin',
                         'Metal',
                         'Comedy',
                         'Country & Folk',
                         'R&B',
                         'Rock',
                         'Music',
                         'Punk',
                         'Electronic Music',
             'not considered'],
                      'Photography': 
                      ['Photobooks',
                         'Animals',
                         'Places',
                         'Nature',
                         'People',
                         'Fine Art',
                         'Photography',
             'not considered'],
                      'Publishing': 
                      ['Radio & Podcasts',
                         'Art Books',
                         'Literary Journals',
                         'Poetry',
                         'Calendars',
                         'Comedy',
                         'Letterpress',
                         'Literary Spaces',
                         "Children's Books",
                         'Zines',
                         'Academic',
                         'Publishing',
                         'Anthologies',
                         'Periodicals',
                         'Nonfiction',
                         'Fiction',
                         'Translations',
                         'Young Adult',
             'not considered'],
                      'Technology': 
                          ['Technology',
                         'Wearables',
                         'Apps',
                         'Space Exploration',
                         'Sound',
                         'Gadgets',
                         'Software',
                         '3D Printing',
                         'Robots',
                         'DIY Electronics',
                         'Hardware',
                         'Web',
                         'Makerspaces',
                         'Camera Equipment',
                         'Flight',
                         'Fabrication Tools',
             'not considered'],
                      'Theater': 
                      ['Spaces',
                         'Comedy',
                         'Festivals',
                         'Experimental',
                         'Musical',
                         'Theater',
                         'Plays',
                         'Immersive',
             'not considered']}
                      
    sub_category.options = list(sub_categories[main_category.value]) # w tym miejscu ustawiamy parametr dropdowna

# a tutaj ustawiamy ciągły nasłuch zmian w wyborze głównej kategorii i wywołanie funkcji zmiany parametru narrow_subcat
main_category.observe(narrow_subcat) 

# widget wyboru kraju
country = widgets.Dropdown(
    options=['Australia',
             'Austria',
             'France',
             'Switzerland',
             'Belgium',
             'Denmark',
             'Canada',
             'Singapore',
             'New Zealand',
             'Hong Kong',
             'Sweden',
             'Germany',
             'Ireland',
             'Luxembourg',
             'Japan',
             'Netherlands',
             'Italy',
             'Great Britain (UK)',
             'Spain',
             'United States',
             'Mexico',
             'Norway',
             'Poland',
             'Other'],
    value="United States",
    description="Country",
    disabled=False,
)

# widget wyboru ile chcemy zebrać w kampanii
goal = widgets.BoundedIntText(
    value=1,
    min=0,
    max=1000000000,
    step=1,
    description="Goal",
    disabled=False
)

# widget wyboru waluty
currency = widgets.Dropdown(
    options=['HKD','SGD','SEK','JPY','NOK','AUD','GBP','CHF','MXN','CAD','DKK','EUR','NZD','USD','PLN'],
    value='USD',
    description="Currency",
    disabled=False,
)

# widget wyboru czasu trwania kampanii
duration = widgets.IntSlider(
    min=1,
    max=90,
    step=1,
    value = 30,
    description='Duration',
    disabled=False,
    continuous_update=True,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)

# widget do wpisania nazwy kamapanii
campaign_name = widgets.Text(
    value='Kickstarter Campaign',
    placeholder='Type something',
    description='Name',
    disabled=False
)
